---
- hosts: all
  become: true

  tasks:
    - name: Install Apache in Fedora
      dnf:
        name: httpd
        state: present
        update_cache: yes
      when: ansible_distribution == "Fedora"

    - name: Starting Apache service in Fedora
      systemd:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "Fedora"

    - name: Install Apache in ubuntu
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
