---
- hosts: all
  become: true
  pre_tasks:
    - name: Updating Cache in Fedora
      tags: always
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "Fedora"

    - name: Updating Cache in Ubuntu
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true

  tasks:
    - name: Install Apache in Fedora
      tags: apache,httpd,fedora
      dnf:
        name: httpd
        state: latest
      when: ansible_distribution == "Fedora"

    - name: Starting Apache service in Fedora
      tags: apache,httpd,fedora
      systemd:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "Fedora"

    - name: Install Apache in Ubuntu
      tags: apache,apache2,ubuntu
      apt:
        name: apache2
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Copying the custom html file
      tags: apache,apache2,httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

- hosts: db_servers
  become: true
  tasks:
    - name: Installing MariaDb in Fedora
      tags: db,mariadb
      package:
        name: mariadb-server
        state: latest

    - name: Starting Maridb Service in Fedora
      tags: db,mariadb,fedora
      systemd:
        name: mariadb
        state: started
        enabled: yes
      when: ansible_distribution == "Fedora"

- hosts: file_servers
  become: true
  tasks:
    - name: Installing Samba
      tags: samba
      package:
        name: samba
        state: latest

    - name: Starting Samba Service in Fedora
      tags: samba,fedora
      systemd:
        name: smb
        state: started
        enabled: yes
      when: ansible_distribution == "Fedora"
