---
- hosts: all
  become: true
  pre_tasks:
    - name: Updating Cache in Fedora
      tags: always
      dnf:
        update_cache: yes
      when: ansible_distribution == "Fedora"
      changed_when: false

    - name: Updating Cache in Ubuntu
      tags: always
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
      changed_when: false

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers

- hosts: workstation
  become: true
  roles:
    - workstation
