---
- name: playbook to uninstall httpd
  hosts: all
  become: yes
  tasks:
    - name: Remove Apache package
      dnf:
        name: httpd
        state: absent
        autoremove: yes
      when: ansible_distribution == "Fedora"

    - name: Remove Apache package
      apt:
        name: apache2
        state: absent
        autoremove: yes
      when: ansible_distribution == "Ubuntu"
