- name: Install Apache in Fedora
  tags: apache,httpd,fedora
  dnf:
    name: "{{apache_package}}"
    state: latest
  when: ansible_distribution == "Fedora"

- name: Starting Apache service in Fedora
  tags: apache,httpd,fedora
  systemd:
    name: "{{apache_service}}"
    state: started
    enabled: yes
  when: ansible_distribution == "Fedora"

- name: Install Apache in Ubuntu
  tags: apache,apache2,ubuntu
  apt:
    name: "{{apache_package}}"
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Copying the custom html file
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: Chaingin the emal in httpd.conf
  tags: apache,httpd,fedora
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: "^ServerAdmin"
    line: ServerAdmin linus@torvald
  notify: restart_apache
  when: ansible_distribution == "Fedora"
